# Generated by Django 5.1.6 on 2025-02-25 17:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feca_web_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='path/to/default/image.png', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
